# We are going to use short-lived JWT, so we do not want to create this secret
# cat sa-secret-template.yaml | ns=sales name=sales-auth envsubst | kubectl apply -f -
# cat sa-secret-template.yaml | ns=engineering name=eng-auth envsubst | kubectl apply -f -
---
apiVersion: v1
kind: Secret
metadata:
  name: $name-with-token
  namespace: $ns
  annotations:
    kubernetes.io/service-account.name: $name
type: kubernetes.io/service-account-token
