# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ab"
  config.vm.network "public_network", ip: "192.168.2.122", bridge: "eth0"

  config.vm.provider "virtualbox" do |v|
    v.name = "ab"
    v.customize ["modifyvm", :id, "--memory","1024" ]
    v.customize ["modifyvm", :id, "--cpus","1" ]
  end

  #config.vm.synced_folder "/home/fabian/Documents", "/Documents"

  config.vm.provision "shell", path: "ab.sh", privileged: true

end
