# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ab"
  config.vm.network "public_network", ip: "192.168.2.122", bridge: "eth0"

  config.vm.provider "virtualbox" do |v|
    v.name = "ab"
    v.customize ["modifyvm", :id, "--memory","1024" ]
    v.customize ["modifyvm", :id, "--cpus","1" ]
  end

  #config.vm.synced_folder "/home/fabian/Documents", "/Documents"
  #config.vm.provision "shell", path: "ab.sh", privileged: true

  config.vm.provision "shell", inline: <<-SHELL
apt-get update -q

cd /usr/src
wget http://apache.mirrors.pair.com/httpd/httpd-2.4.33.tar.gz
tar xfz httpd-2.4.33.tar.gz
cd httpd-2.4.33

cp support/ab.c support/ab.c.old
wget https://raw.githubusercontent.com/fabianlee/blogcode/master/haproxy/ab.c -O support/ab.c

apt-get install libapr1-dev libaprutil1-dev libpcre3 libpcre3-dev -y
./configure
make

support/ab -V

cp support/ab /usr/sbin/ab

ab -V

SHELL

end
