# -*- mode: ruby -*-
# vi: set ft=ruby :

vmname = 'aptcacherng'
boxname = 'ubuntu/xenial64'

Vagrant.configure(2) do |config|
  config.vm.hostname = "#{vmname}"
  config.vm.box = "#{boxname}"
  config.vm.network "public_network", ip: "192.168.2.125", bridge: "eth0"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |v|
    v.name = "#{vmname}"
    v.customize ["modifyvm", :id, "--memory","1024" ]
    v.customize ["modifyvm", :id, "--cpus","1" ]
  end

  config.vm.synced_folder "/home/fabian/Documents", "/Documents"

  config.vm.provision "shell", path: "aptcacherng.sh", privileged: false

  config.vm.provision "shell", inline: <<-SHELL
#apt-get update -q
echo "DONE" >> /tmp/done.txt
SHELL

end
