# use 'with_filetree' lookup plugin (fully qualified is 'with_community.general.filetree')
# to create deep directory structure of templates
---

- set_fact:
    dest_dir: /tmp/filetreetest

- name: Create directory structure
  file:
    path: '{{dest_dir}}/{{ item.path }}'
    state: directory
    mode: '{{ item.mode }}'
  #with_community.general.filetree:
  with_filetree: '{{role_path}}/templates/'
  loop_control:
    label: '{{item.path}}'
  when: item.state == 'directory'

- name: show Template files
  debug:
    msg: 'dest={{dest_dir}}/{{ item.path }}'
  with_filetree: '{{role_path}}/templates/'
  loop_control:
    label: '{{item.path}}"'
  when: item.state == 'file'

- name: Generate Template files with directory structure
  template:
    src: '{{ item.src }}'
    dest: '{{dest_dir}}/{{ item.path }}'
    mode: '{{ item.mode }}'
  #with_community.general.filetree
  with_filetree: '{{role_path}}/templates/'
  loop_control:
    label: '{{item.path}}'
  when: item.state == 'file'
