#
# Used as template for sidecar injection with HashiCorp Vault for secret access
#
#export app=tiny-tools-mytest-vault
#export namespace_k8s=vault
#export service_account_k8s=vault-auth
#export vault_role=myrole
#export vault_secret_path=secret/webapp/config
#
# generate:
# cat tiny-tools.yaml | DOLLAR_SIGN='$' envsubst | kubectl apply -f -
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $app
  namespace: $namespace_k8s
  labels:
    app: $app
spec:
  selector:
    matchLabels:
      app: $app
  replicas: 1
  template:
    metadata:
      labels:
        app: $app
      annotations:
        #sidecar.istio.io/inject: "true"

        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-init-first: 'false'
        vault.hashicorp.com/agent-cache-enable: 'true'
        vault.hashicorp.com/auth-type: 'kubernetes'
        vault.hashicorp.com/auth-config-path: '/var/run/secrets/kubernetes.io/serviceaccount/token'
        vault.hashicorp.com/remove-jwt-after-reading : 'false'
        vault.hashicorp.com/auth-path: auth/kubernetes
        vault.hashicorp.com/role: $vault_role
        #vault.hashicorp.com/namespace: $namespace_vault # only available to Vault Enterprise

        # https://developer.hashicorp.com/vault/tutorials/kubernetes/kubernetes-sidecar#inject-secrets-into-the-pod
        # write secret to file
        vault.hashicorp.com/agent-inject-secret-mysecretdump: $vault_secret_path
        vault.hashicorp.com/agent-inject-file-mysecretdump: mysecret.dump

        # write into filesystem of container, formatted as we choose
        vault.hashicorp.com/agent-inject-secret-mysecret.txt: $vault_secret_path
        vault.hashicorp.com/agent-inject-template-mysecret.txt: |
          {{- with secret "$vault_secret_path" -}}
          {{- range ${DOLLAR_SIGN}k, ${DOLLAR_SIGN}v := .Data.data -}}
          {{ ${DOLLAR_SIGN}k }} = {{ ${DOLLAR_SIGN}v }}
          {{ end }}
          {{- end -}}

    spec:
      serviceAccountName: $service_account_k8s

      containers:
      - name: tiny-tools
        image: giantswarm/tiny-tools:3.12
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; date; echo "starting..."; sleep 30d
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
