# https://github.com/hashicorp/vault-secrets-operator/blob/main/chart/crds/secrets.hashicorp.com_vaultstaticsecrets.yaml
# https://github.com/hashicorp/vault-secrets-operator/tree/main/config/samples
# https://developer.hashicorp.com/vault/docs/platform/k8s/vso/api-reference#vaultstaticsecretspec
# cat vaultstaticsecret-hello.yaml | envsubst | kubectl apply -f -
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-staticsecret-hello
spec:
  vaultAuthRef: vso-jwt-auth #$vso_ns/vso-jwt-auth
  mount: secret
  type: kv-v2
  path: webapp/hello
  refreshAfter: 10s
  hmacSecretData: true
  rolloutRestartTargets:
    - kind: Deployment
      name: web-hello
  destination:
    create: true
    name: hello-secret
