# https://github.com/hashicorp/vault-secrets-operator/blob/main/chart/crds/secrets.hashicorp.com_vaultstaticsecrets.yaml
# https://github.com/hashicorp/vault-secrets-operator/tree/main/config/samples
# https://developer.hashicorp.com/vault/docs/platform/k8s/vso/api-reference#vaultstaticsecretspec
# kubectl apply -f vaultstaticsecret-cert.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-staticsecret-cert
spec:
  vaultAuthRef: vso-jwt-auth
  mount: secret
  type: kv-v2
  path: webapp/cert
  refreshAfter: 10s
  hmacSecretData: true
  destination:
    create: true
    name: cert-secret
    type: kubernetes.io/tls
