---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: my-tls-secret-extfile
  #namespace: default
behavior: create
files:
  - tls.crt=my-tls.crt
  - tls.key=my-tls.key
type: kubernetes.io/tls
options:
  disableNameSuffixHash: true
