# -*- mode: ruby -*-
# vi: set ft=ruby :
#
#
vmname = 'gpg1604'
boxname = 'ubuntu/xenial64'

Vagrant.configure(2) do |config|
  config.vm.hostname = "#{vmname}"
  config.vm.box = "#{boxname}"
  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |v|
    v.name = "#{vmname}"
    v.customize ["modifyvm", :id, "--memory","1024" ]
    v.customize ["modifyvm", :id, "--cpus","1" ]
  end

  config.vm.provision "shell", path: "gpgsetup.sh", privileged: false
  config.vm.provision "shell", path: "createsecret.sh", privileged: false
  config.vm.provision "shell", path: "fordevelopers.sh", privileged: false

  config.vm.provision "shell", inline: <<-SHELL

echo "SUCCESS!"

SHELL

end
