---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# for testing:
# kubectl kustomize . --enable-helm
# kubectl get serviceaccount default -n default -o=yaml
#
# to apply:
# kubectl apply -k .
# OR
# kubectl kustomize . --enable-helm | kubectl apply -f -

resources:
  - sa.yaml

#components:

patches:
  - path: sa-patch.yaml
